In [663]:
import os
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D, LSTM, Dense, Flatten
from keras.utils import to_categorical
import matplotlib.pyplot as plt

In [664]:
folder_path = 'C:\\Users\\Administrator\\Documents\\TA\\dataset_feature_extracted\\'

In [665]:
train_folder = 'C:\\Users\\Administrator\\Documents\\TA\\dataset_feature_extracted\\training_set'
test_folder = 'C:\\Users\\Administrator\\Documents\\TA\\dataset_feature_extracted\\test_set'

Delete NaN Row

In [666]:
# def delete_nan_row(file_path):
#     df = pd.read_csv(file_path)

#     df = df.dropna()

#     df.to_csv(file_path, index=False)

# file_list = os.listdir(folder_path)

# for file_name in file_list:
#     if file_name.endswith('.csv'):
#         file_path = os.path.join(folder_path, file_name)
#         delete_nan_row(file_path)

# print("Proses selesai.")

Test Train Split

In [667]:
df = pd.read_csv(f'C:\\Users\\Administrator\\Documents\\TA\\dataset_feature_extracted\\record_234.csv')
df

-0.030152248136945094  -0.03129671196431144  -0.033155618102112885  \
0                 0.001585              0.002503               0.001177   
1                -0.004904             -0.005615              -0.007241   
2                 0.000523             -0.000774              -0.001968   
3                 0.016710              0.014220               0.011729   
4                -0.014683             -0.014829              -0.014364   
..                     ...                   ...                    ...   
375              -0.037304             -0.041972              -0.047252   
376              -0.011085             -0.017233              -0.024811   
377              -0.053734             -0.052726              -0.051410   
378              -0.057232             -0.057319              -0.058018   
379              -0.009802             -0.015868              -0.021219   

     -0.03460652994117155  -0.03595558226388204  -0.037406868998652414  \
0               -0.001883             -0.005452              -0.009429   
1               -0.009579             -0.012220              -0.015266   
2               -0.002957             -0.004353              -0.006463   
3                0.009035              0.005728               0.002523   
4               -0.013900             -0.014457              -0.016546   
..                    ...                   ...                    ...   
375             -0.052430             -0.056179              -0.058907   
376             -0.033206             -0.041499              -0.048569   
377             -0.050399             -0.050102              -0.050926   
378             -0.060043             -0.063905              -0.068684   
379             -0.025550             -0.028656              -0.030537   

     -0.03845019832128739  -0.038575378368619864  -0.038190584584798924  \
0               -0.012793              -0.015237              -0.016660   
1               -0.018412              -0.020636              -0.021837   
2               -0.008674              -0.011395              -0.014216   
3               -0.000579              -0.003171              -0.005559   
4               -0.019758              -0.024501              -0.029756   
..                    ...                    ...                    ...   
375             -0.060207              -0.060385              -0.059644   
376             -0.053190              -0.055670              -0.056007   
377             -0.052565              -0.054815              -0.057370   
378             -0.073565              -0.078343              -0.082203   
379             -0.031602              -0.032565              -0.033527   

     -0.03770399237370384  ...  -0.03746227229317079  -0.036409898734004645  \
0               -0.017062  ...             -0.004723              -0.003545   
1               -0.022423  ...             -0.060561              -0.063127   
2               -0.017037  ...             -0.023473              -0.026637   
3               -0.007437  ...             -0.019758              -0.024501   
4               -0.034808  ...             -0.053472              -0.055516   
..                    ...  ...                   ...                    ...   
375             -0.057882  ...             -0.029948              -0.031462   
376             -0.054610  ...             -0.040138              -0.042895   
377             -0.059822  ...             -0.068684              -0.073565   
378             -0.084021  ...             -0.066639              -0.071012   
379             -0.035204  ...             -0.060536              -0.060373   

     -0.03484838895852271  -0.0336961039454009  -0.03315711889318983  \
0               -0.002980            -0.003639             -0.005727   
1               -0.064774            -0.065095             -0.063885   
2               -0.029392            -0.031021             -0.030914   
3               -0.029756            -0.034808             -0.039248   
4    

In [668]:
record_names = ['100', '101', '102', '103', '104', '105', '106', '107', '108', '109', '111', '112', '113', '114', '115', '116', '117', '118', '119', '121', '122', '123', '124', '200', '201', '202', '203', '205', '207', '208', '209', '210', '212', '213', '214', '215', '217', '219', '220', '221', '222', '223', '228', '230', '231', '232', '233', '234']

for record_name in record_names:
    df = pd.read_csv(f'C:\\Users\\Administrator\\Documents\\TA\\dataset_feature_extracted\\record_{record_name}.csv')
    df.head()

    unique_labels = df.iloc[:, -1].unique()
    print(record_name, unique_labels)

100 ['N' 'A' 'V']
101 ['N' 'A']
102 ['V' 'N']
103 ['N' 'A']
104 ['N' 'V']
105 ['N' 'V']
106 ['N' 'V']
107 ['V']
108 ['N' 'V' 'A' 'F']
109 ['L' 'F' 'V']
111 ['L' 'V']
112 ['N' 'A']
113 ['N' 'a']
114 ['N' 'V' 'J' 'F' 'A']
115 ['N']
116 ['N' 'V' 'A']
117 ['N' 'A']
118 ['R' 'V' 'A']
119 ['V' 'N']
121 ['N' 'A' 'V']
122 ['N']
123 ['N']
124 ['R' 'J' 'V' 'F' 'A']
200 ['V' 'N' 'A' 'F']
201 ['N' 'a' 'V' 'A' 'J' 'F']
202 ['N' 'V' 'A' 'a' 'F']
203 ['N' 'V' 'a']
205 ['N' 'V' 'F' 'A']
207 ['V' 'R' 'L' 'E' 'A']
208 ['V' 'F' 'N']
209 ['N' 'A' 'V']
210 ['N' 'F' 'V' 'a' 'E']
212 ['R' 'N']
213 ['N' 'F' 'A' 'V' 'a']
214 ['L' 'V' 'F']
215 ['N' 'V' 'A']
217 ['V' 'N']
219 ['N' 'V' 'F' 'A']
220 ['N' 'A']
221 ['N' 'V']
222 ['N' 'A' 'J']
223 ['N' 'V' 'A' 'F' 'a']
228 ['N' 'V' 'A']
230 ['N' 'V']
231 ['R' 'N' 'A']
232 ['R' 'A']
233 ['V' 'N' 'A' 'F']
234 ['N' 'J']


Split Train and Test Phase

In [669]:
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

dfs = []

for csv_file in csv_files:
    file_path = os.path.join(folder_path, csv_file)
    
    df = pd.read_csv(file_path, header=None)

    dfs.append(df)

combined_data = pd.concat(dfs, ignore_index=True)

X = combined_data.iloc[:, :-1] 
y = combined_data.iloc[:, -1]

In [670]:
X

0         1         2         3         4         5         6    \
0     -0.062349 -0.059537 -0.055399 -0.050137 -0.044365 -0.037571 -0.030063   
1      0.005020  0.005367  0.006225  0.007388  0.008346  0.009100  0.009752   
2     -0.014524 -0.013170 -0.012224 -0.012094 -0.012678 -0.014384 -0.016906   
3      0.000127 -0.001334 -0.002896 -0.004865 -0.006834 -0.009414 -0.011586   
4      0.013770  0.014504  0.015136  0.015563  0.015480  0.014989  0.014294   
...         ...       ...       ...       ...       ...       ...       ...   
32013 -0.037304 -0.041972 -0.047252 -0.052430 -0.056179 -0.058907 -0.060207   
32014 -0.011085 -0.017233 -0.024811 -0.033206 -0.041499 -0.048569 -0.053190   
32015 -0.053734 -0.052726 -0.051410 -0.050399 -0.050102 -0.050926 -0.052565   
32016 -0.057232 -0.057319 -0.058018 -0.060043 -0.063905 -0.068684 -0.073565   
32017 -0.009802 -0.015868 -0.021219 -0.025550 -0.028656 -0.030537 -0.031602   

            7         8         9    ...       246       247       248  \
0     -0.021636 -0.013412 -0.005289  ... -0.006234 -0.001522  0.002985   
1      0.010505  0.010952  0.010990  ...  0.018429  0.022188  0.025436   
2     -0.019734 -0.022051 -0.024061  ...  0.014605  0.019910  0.025521   
3     -0.013349 -0.014805 -0.016056  ...  0.015729  0.017746  0.019151   
4      0.012883  0.011065  0.008532  ...  0.004796  0.009466  0.013014   
...         ...       ...       ...  ...       ...       ...       ...   
32013 -0.060385 -0.059644 -0.057882  ... -0.026597 -0.029948 -0.031462   
32014 -0.055670 -0.056007 -0.054610  ... -0.036767 -0.040138 -0.042895   
32015 -0.054815 -0.057370 -0.059822  ... -0.063905 -0.068684 -0.073565   
32016 -0.078343 -0.082203 -0.084021  ... -0.061757 -0.066639 -0.071012   
32017 -0.032565 -0.033527 -0.035204  ... -0.060293 -0.060536 -0.060373   

            249       250       251       252       253       254       255  
0      0.007697  0.012204  0.016507  0.020197  0.022663  0.024108  0.024635  
1      0.028786  0.031932  0.034975  0.037611  0.040144  0.041963  0.043578  
2      0.030724  0.034804  0.037864  0.039700  0.040413  0.040106  0.038778  
3      0.019639  0.019821  0.018984  0.017535  0.016393  0.015558  0.014723  
4      0.016153  0.018884  0.021105  0.023122  0.025138  0.026747  0.028355  
...         ...       ...       ...       ...       ...       ...       ...  
32013 -0.031753 -0.031330 -0.030602 -0.030181 -0.029761 -0.029750 -0.030453  
32014 -0.044733 -0.045752 -0.046566 -0.047175 -0.047884 -0.048490 -0.048686  
32015 -0.078343 -0.082203 -0.084021 -0.082981 -0.078982 -0.073656 -0.068635  
32016 -0.074058 -0.075063 -0.074539 -0.072688 -0.070327 -0.068375 -0.067342  
32017 -0.060618 -0.061884 -0.063457 -0.065031 -0.066095 -0.066548 -0.066083  

[32018 rows x 256 columns]

In [671]:
y

0        A
1        N
2        N
3        N
4        N
        ..
32013    N
32014    N
32015    N
32016    N
32017    N
Name: 256, Length: 32018, dtype: object

In [672]:
y.unique()

array(['A', 'N', 'V', 'F', 'L', 'a', 'J', 'R', 'E'], dtype=object)

In [673]:
y = LabelEncoder().fit_transform(y)
y

array([0, 5, 5, ..., 5, 5, 5])

In [674]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [675]:
y_train

array([4, 4, 5, ..., 5, 7, 4])

In [676]:
y_test

array([7, 6, 6, ..., 4, 4, 6])

In [677]:
y_test = LabelEncoder().fit_transform(y_test)
y_test

array([7, 6, 6, ..., 4, 4, 6], dtype=int64)

Classification Phase

In [678]:
labels = ['A', 'N', 'V', 'F', 'L', 'a', 'J', 'R', 'E']
num_classes = len(labels)

#1 CLSTM